// Structured question bank for "Great Minds Think Alike"
// { id, question, category, intensity: 'safe'|'spicy'|'chaotic', answerType: 'word'|'phrase'|'person', tags }

const QUESTIONS = [
  { id: 1, question: 'Vad är det bästa man kan säga för att avsluta en första dejt?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating', 'breakup'] },
  { id: 2, question: 'Vad gör du först om du ser ditt ex på ICA?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating', 'ex'] },
  { id: 3, question: 'Vad är den viktigaste egenskapen hos en perfekt partner?', category: 'dating', intensity: 'safe', answerType: 'word', tags: ['dating', 'partner'] },
  { id: 4, question: 'Hur skulle ditt ex beskriva dig med ett ord?', category: 'dating', intensity: 'safe', answerType: 'word', tags: ['dating', 'ex'] },
  { id: 5, question: 'Vad är det värsta som kan hända på en första dejt?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating'] },
  { id: 6, question: 'Hur vet man att man är kär?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating', 'love'] },
  { id: 7, question: 'Vad är en deal breaker i ett förhållande?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating', 'relationship'] },
  { id: 8, question: 'Vad är det största varningstecknet på en första dejt?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating'] },
  { id: 9, question: 'Vad är den mest romantiska gesten någon kan göra?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating', 'romance'] },
  { id: 10, question: 'Vad är det mest avtändande någon kan göra?', category: 'dating', intensity: 'spicy', answerType: 'phrase', tags: ['dating', 'turnoff'] },
  { id: 11, question: 'Vad är en perfekt första dejt?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating'] },
  { id: 12, question: 'En dålig raggningsreplik?', category: 'dating', intensity: 'spicy', answerType: 'phrase', tags: ['dating', 'flirting'] },
  { id: 13, question: 'Vad är det första du gör när du får någons nummer?', category: 'dating', intensity: 'safe', answerType: 'phrase', tags: ['dating'] },
  { id: 14, question: 'Vad är något folk ljuger om på dejtingappar?', category: 'dating', intensity: 'spicy', answerType: 'phrase', tags: ['dating', 'apps'] },
  { id: 15, question: 'Vilket djur skulle ha sämst rykte på Tinder?', category: 'dating', intensity: 'chaotic', answerType: 'word', tags: ['dating', 'animal'] },

  { id: 16, question: 'Vilken plats borde man absolut inte ha sex på?', category: 'spicy', intensity: 'spicy', answerType: 'phrase', tags: ['spicy', 'sex'] },
  { id: 17, question: 'Något som dödar stämningen direkt i sovrummet?', category: 'spicy', intensity: 'spicy', answerType: 'phrase', tags: ['spicy', 'bedroom'] },
  { id: 18, question: 'Vad är den största ick-faktorn i dejting?', category: 'spicy', intensity: 'spicy', answerType: 'phrase', tags: ['spicy', 'dating'] },
  { id: 19, question: 'Vad är något som låter oskyldigt men inte är det?', category: 'spicy', intensity: 'spicy', answerType: 'word', tags: ['spicy', 'innuendo'] },
  { id: 20, question: 'Vad förstör en flirt direkt?', category: 'spicy', intensity: 'safe', answerType: 'phrase', tags: ['spicy', 'flirting'] },

  { id: 21, question: 'Vad är den sämsta ursäkten för att komma sent till jobbet?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'excuse'] },
  { id: 22, question: 'Vad är en vanlig ursäkt för att komma sent?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'excuse'] },
  { id: 23, question: 'Vad gör du först när du kommer hem från jobbet?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'routine'] },
  { id: 24, question: 'Vad är det värsta med måndagar?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'monday'] },
  { id: 25, question: 'Vad är en klassisk ursäkt för att slippa jobb?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'excuse'] },
  { id: 26, question: 'Vad är bästa sättet att få lönehöjning?', category: 'work', intensity: 'safe', answerType: 'phrase', tags: ['work', 'salary'] },

  { id: 27, question: 'Vad köper du först om du vinner 10 miljoner?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money', 'lottery'] },
  { id: 28, question: 'Vilket jobb skulle du ha om lönen inte spelade roll?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money', 'job'] },
  { id: 29, question: 'Vad är ditt drömresemål?', category: 'money', intensity: 'safe', answerType: 'word', tags: ['money', 'travel'] },
  { id: 30, question: 'Vad skulle du göra om du blev ekonomiskt fri imorgon?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money'] },
  { id: 31, question: 'Vad är den mest onödiga lyxen man kan köpa?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money', 'luxury'] },
  { id: 32, question: 'Vad är något alla skulle köpa om de blev rika?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money'] },
  { id: 33, question: 'Vad är det dyraste du skulle köpa direkt?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money'] },
  { id: 34, question: 'Vad är det mest onödiga du brukar köpa?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money'] },
  { id: 35, question: 'Ett sätt att tjäna pengar förutom lön?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money'] },
  { id: 36, question: 'Det första att betala när lönen trillar in på kontot?', category: 'money', intensity: 'safe', answerType: 'phrase', tags: ['money', 'salary'] },

  { id: 37, question: 'Vilken superkraft vill du ha?', category: 'absurd', intensity: 'safe', answerType: 'word', tags: ['absurd', 'superpower'] },
  { id: 38, question: 'Vilken superkraft är helt värdelös?', category: 'absurd', intensity: 'chaotic', answerType: 'word', tags: ['absurd', 'superpower'] },
  { id: 39, question: 'Vilket djur skulle bli bäst diktator?', category: 'absurd', intensity: 'chaotic', answerType: 'word', tags: ['absurd', 'animal'] },
  { id: 40, question: 'Vilken färg skulle du vara om du var en alien?', category: 'absurd', intensity: 'chaotic', answerType: 'word', tags: ['absurd', 'alien'] },
  { id: 41, question: 'Vad skulle aliens tycka är konstigast med människor?', category: 'absurd', intensity: 'chaotic', answerType: 'phrase', tags: ['absurd', 'alien'] },
  { id: 42, question: 'En planet du hade velat landa på?', category: 'absurd', intensity: 'chaotic', answerType: 'word', tags: ['absurd', 'space'] },
  { id: 43, question: 'Vilken färg ska vi måla huset?', category: 'absurd', intensity: 'chaotic', answerType: 'word', tags: ['absurd'] },
  { id: 44, question: 'En position på fotbollsplanen du vägrar att spela?', category: 'absurd', intensity: 'safe', answerType: 'word', tags: ['absurd', 'sports'] },
  { id: 45, question: 'Om du måste begå ett brott, vad skulle det vara?', category: 'absurd', intensity: 'chaotic', answerType: 'phrase', tags: ['absurd', 'crime'] },

  { id: 46, question: 'Vad är den sämsta pizzatoppingen?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'pizza'] },
  { id: 47, question: 'Vad är bästa bakismaten?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'hangover'] },
  { id: 48, question: 'Vad är ditt bästa natt-snack?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'snack'] },
  { id: 49, question: 'Vad är den mest beroendeframkallande maten?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food'] },
  { id: 50, question: 'Vad skulle du aldrig vilja äta igen?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food'] },
  { id: 51, question: 'Vad är den bästa frukosten?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'breakfast'] },
  { id: 52, question: 'Vad är något du alltid beställer på restaurang?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'restaurant'] },
  { id: 53, question: 'Vad är det första du bakar när du ska bjuda på fika?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'baking'] },
  { id: 54, question: 'Vart kan du handla matvaror?', category: 'food', intensity: 'safe', answerType: 'word', tags: ['food', 'grocery'] },
  { id: 55, question: 'Vad gör man när man inte orkar laga mat?', category: 'food', intensity: 'safe', answerType: 'phrase', tags: ['food'] },

  { id: 56, question: 'Vad är det konstigaste folk gör i smyg?', category: 'embarrassing', intensity: 'spicy', answerType: 'phrase', tags: ['embarrassing', 'secret'] },
  { id: 57, question: 'Vad är det mest pinsamma man kan göra offentligt?', category: 'embarrassing', intensity: 'safe', answerType: 'phrase', tags: ['embarrassing', 'public'] },
  { id: 58, question: 'Vad är det konstigaste du gjort ensam hemma?', category: 'embarrassing', intensity: 'spicy', answerType: 'phrase', tags: ['embarrassing', 'home'] },
  { id: 59, question: 'Vad är det värsta man kan skriva i fel sms?', category: 'embarrassing', intensity: 'spicy', answerType: 'phrase', tags: ['embarrassing', 'texting'] },
  { id: 60, question: 'Vad är något alla gör men ingen erkänner?', category: 'embarrassing', intensity: 'spicy', answerType: 'phrase', tags: ['embarrassing'] },
  { id: 61, question: 'Vad är det pinsammaste som kan hända på en dejt?', category: 'embarrassing', intensity: 'safe', answerType: 'phrase', tags: ['embarrassing', 'dating'] },
  { id: 62, question: 'En lögn du fortfarande trodde på sedan barnsben?', category: 'embarrassing', intensity: 'safe', answerType: 'phrase', tags: ['embarrassing'] },

  { id: 63, question: 'Vad är mest svenskt man kan göra?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'sweden'] },
  { id: 64, question: 'Vad är det mest svenska problemet?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'sweden'] },
  { id: 65, question: 'Vad är det bästa med svensk sommar?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'summer'] },
  { id: 66, question: 'Vad är det värsta med svensk vinter?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'winter'] },
  { id: 67, question: 'Vad är ett typiskt svenskt beteende?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'sweden'] },
  { id: 68, question: 'Vad är något svenskar alltid klagar på?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'sweden'] },
  { id: 69, question: 'Vilket är Sveriges vanligaste yrke?', category: 'culture', intensity: 'safe', answerType: 'word', tags: ['culture', 'sweden'] },
  { id: 70, question: 'Vilken färg är majoriteten av Sveriges bilar?', category: 'culture', intensity: 'safe', answerType: 'word', tags: ['culture', 'sweden'] },
  { id: 71, question: 'Det första du tänker på när du tänker på camping?', category: 'culture', intensity: 'safe', answerType: 'word', tags: ['culture', 'outdoors'] },
  { id: 72, question: 'Den främsta anledningen till att åka till ICA?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'sweden'] },
  { id: 73, question: 'Vad gör du en vinterdag?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'winter'] },
  { id: 74, question: 'Vad händer på julafton?', category: 'culture', intensity: 'safe', answerType: 'phrase', tags: ['culture', 'christmas'] },
  { id: 75, question: 'Något som du hittar på julbordet?', category: 'culture', intensity: 'safe', answerType: 'word', tags: ['culture', 'christmas'] },

  { id: 76, question: 'Vad är något alla låtsas gilla?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social'] },
  { id: 77, question: 'Vad är den mest överdrivna flexen?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'flex'] },
  { id: 78, question: 'Hur avslutar du ett samtal du inte vill ha?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social'] },
  { id: 79, question: 'Hur firar man att det är fredag?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'friday'] },
  { id: 80, question: 'Vad är det värsta som kan hända på en fest?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'party'] },
  { id: 81, question: 'Vad gör du först på en ledig lördag?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'weekend'] },
  { id: 82, question: 'Hur lämnar du en tråkig fest?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'party'] },
  { id: 83, question: 'Vad gör du om du inte känner någon på en fest?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'party'] },
  { id: 84, question: 'Vad gör du först när du kommer till en fest?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'party'] },
  { id: 85, question: 'Vad är det bästa sättet att göra ett första intryck?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social'] },
  { id: 86, question: 'Vad är det första du gör när du vaknar?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'morning'] },
  { id: 87, question: 'Vad är något du alltid glömmer att göra?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social'] },
  { id: 88, question: 'Vad är din mest användbara dåliga vana?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'habit'] },
  { id: 89, question: 'Vad är något du alltid skjuter upp till sista minuten?', category: 'social', intensity: 'safe', answerType: 'phrase', tags: ['social', 'procrastination'] },
  { id: 90, question: 'Ett TV-program du hade medverkat i?', category: 'social', intensity: 'safe', answerType: 'word', tags: ['social', 'tv'] },
  { id: 91, question: 'En podd som går på repeat?', category: 'social', intensity: 'safe', answerType: 'word', tags: ['social', 'podcast'] },

  { id: 92, question: 'Vad är det värsta med sociala medier?', category: 'tech', intensity: 'safe', answerType: 'phrase', tags: ['tech', 'social-media'] },
  { id: 93, question: 'Vad är din mest pinsamma Google-sökning?', category: 'tech', intensity: 'spicy', answerType: 'phrase', tags: ['tech', 'embarrassing'] },
  { id: 94, question: 'Vad skulle du aldrig vilja att din sökhistorik visar?', category: 'tech', intensity: 'spicy', answerType: 'phrase', tags: ['tech'] },
  { id: 95, question: 'Vad är det mest meningslösa du kollat på YouTube?', category: 'tech', intensity: 'safe', answerType: 'phrase', tags: ['tech', 'youtube'] },
  { id: 96, question: 'Vad är det värsta du kan fastna i på TikTok?', category: 'tech', intensity: 'safe', answerType: 'phrase', tags: ['tech', 'tiktok'] },

  { id: 97, question: 'Vad är din definition av lycka?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep', 'happiness'] },
  { id: 98, question: 'Vad tänker du på innan du somnar?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep'] },
  { id: 99, question: 'Vad är det viktigaste du lärt dig om människor?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep'] },
  { id: 100, question: 'Vad ångrar du mest i livet?', category: 'deep', intensity: 'spicy', answerType: 'phrase', tags: ['deep', 'regret'] },
  { id: 101, question: 'Vad är något du aldrig sagt högt?', category: 'deep', intensity: 'spicy', answerType: 'phrase', tags: ['deep', 'secret'] },
  { id: 102, question: 'Vad är det sista du gör innan du somnar?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep', 'night'] },
  { id: 103, question: 'Vad är det mest överskattade i vuxenlivet?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep', 'adulthood'] },
  { id: 104, question: 'Något som gör dig ledsen?', category: 'deep', intensity: 'safe', answerType: 'phrase', tags: ['deep'] },

  { id: 105, question: 'Vem i gruppen skulle överleva längst i en zombieapokalyps?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },
  { id: 106, question: 'Vem i gruppen skulle klara sig bäst på en öde ö?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },
  { id: 107, question: 'Vem i gruppen skulle bli känd först?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },
  { id: 108, question: 'Vem i gruppen skulle hamna i mest trubbel?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },
  { id: 109, question: 'Vem i gruppen blir utslängd först från en bar?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },
  { id: 110, question: 'Vem skulle vinna "Vem vill bli miljonär"?', category: 'group', intensity: 'safe', answerType: 'person', tags: ['group', 'vote'] },

  { id: 111, question: 'Vad är den värsta drycken på fest?', category: 'drinking', intensity: 'safe', answerType: 'word', tags: ['drinking', 'party'] },
  { id: 112, question: 'Vem i gruppen borde ta en shot just nu?', category: 'drinking', intensity: 'chaotic', answerType: 'person', tags: ['drinking', 'group'] },
  { id: 113, question: 'Vem i gruppen borde dricka upp först?', category: 'drinking', intensity: 'chaotic', answerType: 'person', tags: ['drinking', 'group'] },
  { id: 114, question: 'Vad är det bästa sättet att starta en kväll?', category: 'drinking', intensity: 'safe', answerType: 'phrase', tags: ['drinking', 'night'] },
  { id: 115, question: 'En shot som ger dig kväljningar av bara tanken?', category: 'drinking', intensity: 'spicy', answerType: 'word', tags: ['drinking'] },
];

module.exports = { QUESTIONS };
